### ISSUE TITLE
Nuke settings_file.py from orbit

### ISSUE THREAD

**Issue by markrawls** [MetLifeLegalPlans/zygoat#112]
Related to #103 - see there for implementation recommendations.

Stop splitting `settings.py` into `settings/__init__.py` and `settings/zygoat_settings.py`, leave it as `settings.py` as is Django default. If we need to split it into a module, we can do that on a per-app level and add some detection to the few things we have left that modify values in it.

**Comment by kborer** [comment]
instead, add `zygoat-django` as a requirement and create a component that adds `from zygoat_django.settings import *` in the zygoat app's settings file during initialization
