### ISSUE TITLE
Remove fields in default django settings file that conflict with zygoat-django settings

### ISSUE THREAD

**Issue by cviveiro** [MetLifeLegalPlans/zygoat#125]
Basically need to do here automatically what is done in https://github.com/MetLifeLegalPlans/document-generation/pull/25. We don't want those values, we want the zygoat-django values.

Likely you'll want to use redbaron to parse out those lines and delete them.

**Comment by cviveiro** [comment]
for the record, changes would go into `create` in [this file](https://github.com/MetLifeLegalPlans/zygoat/blob/master/zygoat/components/backend/settings/__init__.py)

**Comment by markrawls** [comment]
I accidentally forgot to close this when I did, it's been done for a while.
