### ISSUE TITLE
Show error and exit early when not running in a venv

### ISSUE THREAD

**Issue by cviveiro** [MetLifeLegalPlans/zygoat#134]
got caught by this today, forgot this needs to be run in the project venv. i ran into a permission error and it wasn't clear what was going wrong (thanks @markrawls for debugging).

we should be exiting early when we're not in a venv if it's needed. the trick is figuring out how to detect that. after that, i suspect that this could be a wrapper that wraps all of the necessary shell commands and exits early with an error if you don't have a venv active.

the changes should pretty much be all in this file: https://github.com/MetLifeLegalPlans/zygoat/blob/master/zygoat/cli.py

**Comment by knitHacker** [comment]
Do you still have the command you were having the issue with? Just want to see if I can reproduce the issue and verify that it is fixed. I figure more commands would be affected to but nice to have a starting command.

**Comment by cviveiro** [comment]
Pretty sure it was zg update since that's usually what I run from zygoat

**Comment by cviveiro** [comment]
well, i can't get it to happen again. don't know why it wasn't working this fall but yay for closing issues!
